create database choose_device;
use choose_device;
create table admin (
    admin_id int not null comment '管理员编号',
    admin_account varchar(30) not null comment '管理员账号',
    admin_password varchar(50) not null comment '管理员密码',
    email varchar(45) comment '管理员邮箱',
    role varchar(5) not null comment '管理员权限',
    status int not null default 1 comment '账号状态，0为禁用，1为启用',
    primary key (admin_id),
    unique index uk_admin_account (admin_account)
) engine=innodb;
create table categories (
    category_id int not null auto_increment comment '分类编号',
    category_name varchar(50) not null comment '分类名称',
    parent_id int comment '父级分类编号',
    description varchar(255) comment '分类描述',
    sort_order int default 0 comment '排序号',
    icon varchar(255) comment '分类图标',
    status int not null default 1 comment '分类状态，1启用，0禁用',
    primary key (category_id),
    index idx_categories_parent_id (parent_id),
    foreign key (parent_id) references categories(category_id)
) engine=innodb;
create table brands (
    brand_id int not null auto_increment comment '品牌编号',
    brand_name varchar(50) not null comment '品牌名称',
    logo varchar(255) comment '品牌logo',
    country varchar(50) comment '所属国家',
    website varchar(255) comment '官方网站',
    description text comment '品牌介绍',
    status int not null default 1 comment '品牌状态，1启用，0禁用',
    primary key (brand_id),
    unique index uk_brand_name (brand_name)
) engine=innodb;
create table products (
    product_id int not null auto_increment comment '产品编号',
    product_name varchar(100) not null comment '产品名称',
    category_id int not null comment '分类编号',
    brand_id int not null comment '品牌编号',
    price double not null default 0.00 comment '产品价格',
    description text comment '产品简介',
    view_count int not null default 0 comment '浏览量',
    release_time datetime comment '发布时间',
    status int not null default 1 comment '产品状态',
    primary key (product_id),
    index idx_products_category_id (category_id),
    index idx_products_brand_id (brand_id),
    check (price >= 0),
    foreign key (category_id) references categories(category_id),
    foreign key (brand_id) references brands(brand_id)
) engine=innodb;
create table product_images (
    image_id int not null auto_increment comment '图片编号',
    product_id int not null comment '产品编号',
    image_url varchar(255) not null comment '图片地址',
    image_name varchar(100) comment '图片名称',
    image_type varchar(20) comment '图片类型',
    description text comment '图片描述',
    is_main int not null default 0 comment '是否主图，0否，1是',
    upload_time datetime not null comment '上传时间',
    status int not null default 1 comment '图片状态',
    primary key (image_id),
    index idx_product_images_product_id (product_id),
    foreign key (product_id) references products(product_id)
) engine=innodb;
create table users (
    user_id int not null auto_increment comment '用户编号',
    username varchar(50) not null comment '用户名',
    password varchar(50) not null comment '密码',
    phone varchar(11) not null comment '手机号',
    email varchar(45) comment '邮箱',
    gender varchar(2) comment '性别',
    status int not null default 1 comment '用户状态',
    register_time datetime not null comment '注册时间',
    primary key (user_id),
    unique index uk_username (username)
) engine=innodb;
create table comments (
    comment_id int not null auto_increment comment '评论编号',
    user_id int not null comment '用户编号',
    product_id int not null comment '产品编号',
    content varchar(500) not null comment '评论内容',
    comment_time datetime not null comment '评论时间',
    like_count int not null default 0 comment '点赞数',
    reply_count int not null default 0 comment '回复数',
    status int not null default 1 comment '评论状态',
    primary key (comment_id),
    index idx_comments_user_id (user_id),
    index idx_comments_product_id (product_id),
    foreign key (user_id) references users(user_id),
    foreign key (product_id) references products(product_id)
) engine=innodb;
create table admin_category (
    admin_id int not null comment '管理员编号',
    category_id int not null comment '分类编号',
    primary key (admin_id, category_id),
    index idx_admin_category_category_id (category_id),
    foreign key (admin_id) references admin(admin_id),
    foreign key (category_id) references categories(category_id)
) engine=innodb;
create table admin_brand (
    admin_id int not null comment '管理员编号',
    brand_id int not null comment '品牌编号',
    primary key (admin_id, brand_id),
    index idx_admin_brand_brand_id (brand_id),
    foreign key (admin_id) references admin(admin_id),
    foreign key (brand_id) references brands(brand_id)
) engine=innodb;
create table admin_product (
    admin_id int not null comment '管理员编号',
    product_id int not null comment '产品编号',
    primary key (admin_id, product_id),
    index idx_admin_product_product_id (product_id),
    foreign key (admin_id) references admin(admin_id),
    foreign key (product_id) references products(product_id)
) engine=innodb;
create table favorites (
    favorite_id int not null comment '收藏编号',
    user_id int not null comment '用户编号',
    product_id int not null comment '产品编号',
    favorite_time datetime not null comment '收藏时间',
    status int not null default 1 comment '收藏状态',
    primary key (user_id, product_id),
    unique index uk_favorite_id (favorite_id),
    index idx_favorites_product_id (product_id),
    foreign key (user_id) references users(user_id),
    foreign key (product_id) references products(product_id)
) engine=innodb;
create table admin_comment (
    admin_id int not null comment '管理员编号',
    comment_id int not null comment '评论编号',
    primary key (admin_id, comment_id),
    index idx_admin_comment_comment_id (comment_id),
    foreign key (admin_id) references admin(admin_id),
    foreign key (comment_id) references comments(comment_id)
) engine=innodb;
-- 添加种类
insert into categories (category_name,parent_id,description,sort_order,status)
values('手机',null,'手机类数码产品',1,1),('电脑',null,'电脑类数码产品',2,1);
-- 添加品牌
insert into brands (brand_name, logo, country, website, status)
values
('华为','brand_icon/HUAWEI.png','中国','https://consumer.huawei.com/cn/',1),
('小米','brand_icon/Xiaomi.png','中国','https://www.mi.com/about/index.html',1),
('OPPO','brand_icon/OPPO.svg','中国','https://www.oppo.com/cn/smartphones/',1),
('vivo','brand_icon/Vivo.png','中国','https://www.vivo.com.cn/',1),
('荣耀','brand_icon/Honor.png','中国','https://www.honor.com/cn/phones/',1),
('魅族','brand_icon/MEIZU.png','中国','https://www.meizu.com/index.html',1),
('中兴','brand_icon/ZTE.png','中国','https://www.ztedevices.com/cn/',1),
('Apple','brand_icon/Apple.png','美国','https://www.apple.com.cn/',1),
('三星','brand_icon/Samsung.png','韩国','https://www.samsung.com.cn/',1),
('联想','brand_icon/Lenovo.png','中国','https://www.lenovo.com.cn/',1),
('戴尔','brand_icon/Dell.png','美国','https://www.dell.com/zh-cn',1),
('惠普','brand_icon/HP.png','美国','https://www.hp.com/cn-zh/home.html',1),
('华硕','brand_icon/Asus.png','中国台湾','https://www.asus.com.cn/',1),
('宏碁','brand_icon/acer.png','中国台湾','https://www.acer.com.cn/',1),
('机械革命','brand_icon/MECHREVO.jpg','中国','https://www.mechrevo.com/',1),
('七彩虹','brand_icon/Colorful.jpg','中国','https://www.colorful.cn/',1),
('火影','brand_icon/FIREBAT.png','中国','https://www.firebat.com.cn/',1);

-- 插入手机
insert into products (product_name, category_id, brand_id, price, description, status)
values
('HUAWEI Mate 60', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 4999, '处理器：麒麟9000S；电池容量：4750mAh', 1),
('HUAWEI Mate 60 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 5699, '处理器：麒麟9000S；电池容量：5000mAh', 1),
('HUAWEI Mate 60 Pro+', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 7999, '处理器：麒麟9000S；电池容量：5000mAh', 1),
('HUAWEI Mate 60 RS 非凡大师', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 11999, '处理器：麒麟9000S；电池容量：5000mAh', 1),
('HUAWEI Mate 70', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 5499, '处理器：麒麟9010；电池容量：5300mAh', 1),
('HUAWEI Mate 70 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 6499, '处理器：麒麟9020；电池容量：5500mAh', 1),
('HUAWEI Mate 70 RS 非凡大师', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 11999, '处理器：麒麟9020；电池容量：5700mAh', 1),
('HUAWEI Mate 80', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 4699, '处理器：麒麟9020；电池容量：5750mAh', 1),
('HUAWEI Mate 80 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 5999, '处理器：麒麟9030 / 麒麟9030 Pro；电池容量：5750mAh', 1),
('HUAWEI Mate 80 Pro Max', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 6999, '处理器：麒麟9030 Pro；电池容量：6000mAh', 1),
('HUAWEI Mate 80 RS 非凡大师', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 11999, '处理器：麒麟9030 Pro；电池容量：6000mAh', 1),
('HUAWEI P60', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 4488, '处理器：骁龙8+ Gen1；电池容量：4815mAh', 1),
('HUAWEI P60 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 6188, '处理器：骁龙8+ Gen1；电池容量：4815mAh', 1),
('HUAWEI P60 Art', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 8988, '处理器：骁龙8+ Gen1；电池容量：5060mAh', 1),
('HUAWEI Pura 70', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 4999, '处理器：麒麟9010；电池容量：4900mAh', 1),
('HUAWEI Pura 70 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 5999, '处理器：麒麟9020；电池容量：5050mAh', 1),
('HUAWEI Pura 70 Pro+', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 7499, '处理器：麒麟9020；电池容量：5050mAh', 1),
('HUAWEI Pura 70 Ultra', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 9999, '处理器：麒麟9020；电池容量：5200mAh', 1),
('HUAWEI Pura 80', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 5299, '处理器：官网未标注；电池容量：5600mAh', 1),
('HUAWEI Pura 80 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 6299, '处理器：麒麟9020；电池容量：5700mAh', 1),
('HUAWEI Pura 80 Pro+', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 7699, '处理器：麒麟9020；电池容量：5700mAh', 1),
('HUAWEI Pura 80 Ultra', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 10999, '处理器：麒麟9020；电池容量：5700mAh', 1),
('HUAWEI Pura 90', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 5599, '处理器：麒麟9010S；电池容量：6500mAh', 1),
('HUAWEI Pura 90 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 6599, '处理器：麒麟9030S；电池容量：6000mAh', 1),
('HUAWEI Pura 90 Pro Max', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 7999, '处理器：麒麟9030S；电池容量：6000mAh', 1),
('小米  17', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 4499, '处理器：骁龙 8Elite Gen5；电池容量：7100mAh', 1),
('小米 17 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 5299, '处理器：骁龙 8Elite Gen5；电池容量：6300mAh', 1),
('小米 17 Pro Max', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 5999, '处理器：骁龙 8Elite Gen5；电池容量：7500mAh', 1),
('小米 17 Max', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 0, '处理器：骁龙 8Elite Gen5；电池容量：8000mAh', 1),
('小米 17 Ultra', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 6999, '处理器：骁龙 8Elite Gen5；电池容量：6800mAh', 1),
('小米 17 Ultra徕卡版', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 7499, '处理器：骁龙 8Elite Gen5；电池容量：6800mAh', 1),
('小米 15s Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 5299, '处理器：Xring O1；电池容量：6100mAh', 1),
('小米 15 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 5299, '处理器：骁龙 8 至尊版；电池容量：6100mAh', 1),
('小米 15', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 4499, '处理器：骁龙 8 至尊版；电池容量：5400mAh', 1),
('小米 14 Ultra', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 6499, '处理器：骁龙 8 Gen3；电池容量：5300mAh', 1),
('小米 14 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 4999, '处理器：骁龙 8 Gen3；电池容量：5400mAh', 1),
('小米 14', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 3999, '处理器：骁龙 8 Gen3；电池容量：4610mAh', 1),
('REDMI K90 Max', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 3499, '处理器：天玑9500；电池容量：8550mAh', 1),
('REDMI K90 Pro Max', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 3999, '处理器：骁龙 8 Elite Gen5；电池容量：7500mAh', 1),
('REDMI K90 ', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 2599, '处理器：骁龙 8 至尊版；电池容量：7100mAh', 1),
('Redmi K80 Ultra', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 2599, '处理器：天玑9400+；电池容量：6500mAh', 1),
('Redmi K80 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 3699, '处理器：骁龙 8 至尊版；电池容量：6000mAh', 1),
('Redmi K80', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '小米' limit 1), 2599, '处理器：骁龙 8 Gen3；电池容量：6550mAh', 1),
('OPPO Find X9 Ultra', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'OPPO' limit 1), 7499, '处理器：骁龙8 Elite Gen5；电池容量：7050mAh', 1),
('OPPO Find X9s Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'OPPO' limit 1), 5299, '处理器：天玑 9500；电池容量：7025mAh', 1),
('OPPO Find N6', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'OPPO' limit 1), 9999, '处理器：骁龙8 Elite；电池容量：6000mAh', 1),
('OPPO Find X9 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'OPPO' limit 1), 4799, '处理器：天玑 9500；电池容量：7500mAh', 1),
('OPPO Find X9', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'OPPO' limit 1), 3999, '处理器：天玑 9500；电池容量：7500mAh', 1),
('OPPO Find X8 Ultra', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'OPPO' limit 1), 5999, '处理器：骁龙8 至尊版；电池容量：6100mAh', 1),
('OPPO Find X8s+', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'OPPO' limit 1), 3619, '处理器：天玑 9400+；电池容量：6000mAh', 1),
('OPPO Find X8s', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'OPPO' limit 1), 3399, '处理器：天玑 9400+；电池容量：5700mAh', 1),
('OPPO Find X8 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'OPPO' limit 1), 5299, '处理器：天玑 9400；电池容量：5910mAh', 1),
('OPPO Find X8', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'OPPO' limit 1), 3399, '处理器：天玑 9400；电池容量：5630mAh', 1),
('一加 15', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'OPPO' limit 1), 4499, '处理器：骁龙 8Elite Gen5；电池容量：7300mAh', 1),
('一加 13', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'OPPO' limit 1), 4499, '处理器：骁龙 8 至尊版；电池容量：6000mAh', 1),
('一加 12', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'OPPO' limit 1), 4299, '处理器：骁龙 8 Gen3；电池容量：5400mAh', 1),
('vivo X300 Ultra', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'vivo' limit 1), 6999, '处理器：骁龙 8Elite Gen5；电池容量：6600mAh', 1),
('vivo X300 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'vivo' limit 1), 5599, '处理器：天玑 9500；电池容量：6510mAh', 1),
('vivo X300s', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'vivo' limit 1), 4999, '处理器：天玑 9500；电池容量：7100mAh', 1),
('vivo X300', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'vivo' limit 1), 4599, '处理器：天玑 9500；电池容量：6040mAh', 1),
('iQOO 15', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'vivo' limit 1), 4599, '处理器：骁龙 8Elite Gen5；电池容量：7000mAh', 1),
('iQOO 13', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'vivo' limit 1), 3999, '处理器：骁龙 8 至尊版；电池容量：6150mAh', 1),
('荣耀 Magic7 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '荣耀' limit 1), 5699, '处理器：骁龙 8 至尊版；电池容量：5850mAh', 1),
('魅族 21 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '魅族' limit 1), 4999, '处理器：骁龙 8 Gen 3；电池容量：5050mAh', 1),
('iPhone 17 Pro Max', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 9999, '处理器：A19 Pro；电池容量：4823mAh', 1),
('iPhone 17 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 8999, '处理器：A19 Pro；电池容量：3988mAh', 1),
('iPhone Air', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 7999, '处理器：A19 Pro(5核CPU)；电池容量：3036mAh', 1),
('iPhone 17', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 5999, '处理器：A19；电池容量：3692mAh', 1),
('iPhone 17e', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 4499, '处理器：A19(4核GPU)；电池容量：4005mAh', 1),
('iPhone 16 Pro Max', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 9999, '处理器：A18Pro；电池容量：4685mAh', 1),
('iPhone 16 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 8999, '处理器：A18Pro；电池容量：3582mAh', 1),
('iPhone 16Plus', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 5999, '处理器：A18；电池容量：4674mAh', 1),
('iPhone 16', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 5199, '处理器：A18；电池容量：3561mAh', 1),
('iPhone 16e', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 4499, '处理器：A18；电池容量：3561mAh', 1),
('iPhone 15 Pro Max', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 9999, '处理器：A17Pro；电池容量：4422mAh', 1),
('iPhone 15 Pro', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 8999, '处理器：A17Pro；电池容量：3274mAh', 1),
('iPhone 15Plus', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 5999, '处理器：A16；电池容量：4383mAh', 1),
('iPhone 15', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 5199, '处理器：A16；电池容量：3349mAh', 1),
('Samsung Galaxy S26 Ultra', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '三星' limit 1), 9999, '处理器：骁龙 8Elite Gen5 for Galaxy；电池容量：5000mAh', 1),
('Samsung Galaxy S26+', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '三星' limit 1), 7999, '处理器：骁龙 8Elite Gen5 for Galaxy；电池容量：4900mAh', 1),
('Samsung Galaxy S26', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '三星' limit 1), 5999, '处理器：骁龙 8Elite Gen5 for Galaxy；电池容量：4300mAh', 1),
('Samsung Galaxy S25 Ultra', (select category_id from categories where category_name = '手机' limit 1), (select brand_id from brands where brand_name = '三星' limit 1), 9699, '处理器：骁龙 8 至尊版 for Galaxy；电池容量：5000mAh', 1);
-- 插入手机图片
insert into product_images (product_id, image_url, image_name, image_type, is_main, upload_time, status)
values
((select product_id from products where product_name = 'HUAWEI Mate 60' limit 1), 'phone_image/Mate60.jpg', 'Mate60.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Mate 60 Pro' limit 1), 'phone_image/Mate60 Pro.jpg', 'Mate60 Pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Mate 60 Pro+' limit 1), 'phone_image/Mate60Pro+.jpg', 'Mate60Pro+.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Mate 60 RS 非凡大师' limit 1), 'phone_image/Mate60RS.jpg', 'Mate60RS.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Mate 70' limit 1), 'phone_image/Mate 70.jpg', 'Mate 70.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Mate 70 Pro' limit 1), 'phone_image/mate70pro.jpg', 'mate70pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Mate 70 RS 非凡大师' limit 1), 'phone_image/Mate70RS.png', 'Mate70RS.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Mate 80' limit 1), 'phone_image/Mate 80.png', 'Mate 80.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Mate 80 Pro' limit 1), 'phone_image/Mate 80 Pro.png', 'Mate 80 Pro.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Mate 80 Pro Max' limit 1), 'phone_image/Mate 80 Pro Max.png', 'Mate 80 Pro Max.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Mate 80 RS 非凡大师' limit 1), 'phone_image/Mate80RS.png', 'Mate80RS.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI P60' limit 1), 'phone_image/P60.jpg', 'P60.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI P60 Pro' limit 1), 'phone_image/P60Pro.jpg', 'P60Pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI P60 Art' limit 1), 'phone_image/P60Art.jpg', 'P60Art.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Pura 70' limit 1), 'phone_image/Pura70.jpg', 'Pura70.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Pura 70 Pro' limit 1), 'phone_image/Pura70Pro.jpg', 'Pura70Pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Pura 70 Pro+' limit 1), 'phone_image/Pura70Pro+.jpg', 'Pura70Pro+.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Pura 70 Ultra' limit 1), 'phone_image/Pura70Ultra.jpg', 'Pura70Ultra.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Pura 80' limit 1), 'phone_image/Pura80.jpg', 'Pura80.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Pura 80 Pro' limit 1), 'phone_image/Pura80Pro.jpg', 'Pura80Pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Pura 80 Pro+' limit 1), 'phone_image/Pura80Pro+.jpg', 'Pura80Pro+.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Pura 80 Ultra' limit 1), 'phone_image/Pura80Ultra.jpg', 'Pura80Ultra.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Pura 90' limit 1), 'phone_image/Pura90.jpg', 'Pura90.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Pura 90 Pro' limit 1), 'phone_image/Pura90Pro.jpg', 'Pura90Pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'HUAWEI Pura 90 Pro Max' limit 1), 'phone_image/Pura90ProMax.jpg', 'Pura90ProMax.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '小米  17' limit 1), 'phone_image/xm17.jpg', 'xm17.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '小米 17 Pro' limit 1), 'phone_image/xm17Pro.jpg', 'xm17Pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '小米 17 Pro Max' limit 1), 'phone_image/xm17ProMax.jpg', 'xm17ProMax.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '小米 17 Max' limit 1), 'phone_image/xm17Max.jpg', 'xm17Max.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '小米 17 Ultra' limit 1), 'phone_image/xm17Ultra.jpg', 'xm17Ultra.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '小米 17 Ultra徕卡版' limit 1), 'phone_image/xm17Ultra For LEICA.png', 'xm17Ultra For LEICA.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '小米 15s Pro' limit 1), 'phone_image/xm15sPro.jpg', 'xm15sPro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '小米 15 Pro' limit 1), 'phone_image/xm15Pro.jpg', 'xm15Pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '小米 15' limit 1), 'phone_image/xm15.jpg', 'xm15.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '小米 14 Ultra' limit 1), 'phone_image/xm14Ultra.jpg', 'xm14Ultra.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '小米 14 Pro' limit 1), 'phone_image/xm14Pro.jpg', 'xm14Pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '小米 14' limit 1), 'phone_image/xm14.jpg', 'xm14.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'REDMI K90 Max' limit 1), 'phone_image/K90Max.jpg', 'K90Max.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'REDMI K90 Pro Max' limit 1), 'phone_image/K90ProMax.jpg', 'K90ProMax.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'REDMI K90 ' limit 1), 'phone_image/K90.jpg', 'K90.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'Redmi K80 Ultra' limit 1), 'phone_image/K80Ultra.jpg', 'K80Ultra.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'Redmi K80 Pro' limit 1), 'phone_image/K80Pro.jpg', 'K80Pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'Redmi K80' limit 1), 'phone_image/K80.jpg', 'K80.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'OPPO Find X9 Ultra' limit 1), 'phone_image/FindX9 Ultra.png', 'FindX9 Ultra.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'OPPO Find X9s Pro' limit 1), 'phone_image/FindX9s Pro.png', 'FindX9s Pro.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'OPPO Find N6' limit 1), 'phone_image/FindN6.png', 'FindN6.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'OPPO Find X9 Pro' limit 1), 'phone_image/FindX9 Pro.png', 'FindX9 Pro.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'OPPO Find X9' limit 1), 'phone_image/FindX9.png', 'FindX9.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'OPPO Find X8 Ultra' limit 1), 'phone_image/FindX8 Ultra.png', 'FindX8 Ultra.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'OPPO Find X8s+' limit 1), 'phone_image/FindX8s+.png', 'FindX8s+.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'OPPO Find X8s' limit 1), 'phone_image/FindX8s.png', 'FindX8s.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'OPPO Find X8 Pro' limit 1), 'phone_image/FindX8 Pro.png', 'FindX8 Pro.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'OPPO Find X8' limit 1), 'phone_image/FindX8.png', 'FindX8.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '一加 15' limit 1), 'phone_image/1+15.png', '1+15.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '一加 13' limit 1), 'phone_image/1+13.png', '1+13.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '一加 12' limit 1), 'phone_image/1+12.png', '1+12.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'vivo X300 Ultra' limit 1), 'phone_image/X300Ultra.png', 'X300Ultra.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'vivo X300 Pro' limit 1), 'phone_image/X300Pro.png', 'X300Pro.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'vivo X300s' limit 1), 'phone_image/X300s.png', 'X300s.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'vivo X300' limit 1), 'phone_image/X300.png', 'X300.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'iQOO 15' limit 1), 'phone_image/iQOO15.png', 'iQOO15.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'iQOO 13' limit 1), 'phone_image/iQOO13.png', 'iQOO13.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '荣耀 Magic7 Pro' limit 1), 'phone_image/Magic7Pro.png', 'Magic7Pro.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '魅族 21 Pro' limit 1), 'phone_image/MEIZU 21Pro.jpg', 'MEIZU 21Pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'iPhone 17 Pro Max' limit 1), 'phone_image/17ProMax.jpg', '17ProMax.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'iPhone 17 Pro' limit 1), 'phone_image/17Pro.jpg', '17Pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'iPhone Air' limit 1), 'phone_image/iPhone Air.jpg', 'iPhone Air.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'iPhone 17' limit 1), 'phone_image/17.jpg', '17.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'iPhone 17e' limit 1), 'phone_image/17e.jpg', '17e.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'iPhone 16 Pro Max' limit 1), 'phone_image/16ProMax.png', '16ProMax.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'iPhone 16 Pro' limit 1), 'phone_image/16Pro.png', '16Pro.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'iPhone 16Plus' limit 1), 'phone_image/16Plus.png', '16Plus.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'iPhone 16' limit 1), 'phone_image/16.jpg', '16.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'iPhone 16e' limit 1), 'phone_image/16e.png', '16e.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'iPhone 15 Pro Max' limit 1), 'phone_image/15ProMax.png', '15ProMax.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'iPhone 15 Pro' limit 1), 'phone_image/15Pro.png', '15Pro.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'iPhone 15Plus' limit 1), 'phone_image/15Plus.png', '15Plus.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'iPhone 15' limit 1), 'phone_image/15.png', '15.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'Samsung Galaxy S26 Ultra' limit 1), 'phone_image/Galaxy-S26-Ultra.jpg', 'Galaxy-S26-Ultra.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'Samsung Galaxy S26+' limit 1), 'phone_image/S26.jpg', 'S26.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'Samsung Galaxy S26' limit 1), 'phone_image/S26.jpg', 'S26.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'Samsung Galaxy S25 Ultra' limit 1), 'phone_image/S25Ultra.jpg', 'S25Ultra.jpg', 'jpg', 1, now(), 1);

-- 插入电脑
insert into products (product_name, category_id, brand_id, price, description, status)
values
('MacBook Air 13 (M3)', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 8999, '类型：轻薄本；处理器：Apple M3；显卡：至高 8 核 GPU；内存：16GB；存储：512GB SSD', 1),
('MacBook Pro 14 (M4 Pro)', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 16999, '类型：创作本；处理器：Apple M4 Pro；显卡：至高 16 核 GPU；内存：24GB；存储：1TB SSD', 1),
('MacBook Air 13 (M4)', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 10999, '类型：轻薄本；处理器：Apple M4；显卡：10核图形处理器；内存：24GB；存储：512GB SSD', 1),
('MacBook Pro 13 (M2)', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = 'Apple' limit 1), 9999, '类型：轻薄本；处理器：Apple M2；显卡：10核图形处理器；内存：8GB；存储：256GB SSD', 1),
('ThinkPad X1 Carbon', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '联想' limit 1), 12999, '类型：商务本；处理器：酷睿 Ultra 7-255H；显卡：Intel Arc 140T 核显；内存：32GB；存储：1TB SSD', 1),
('拯救者 Y7000P 2025', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '联想' limit 1), 7999, '类型：游戏本；处理器：酷睿 i7-14700HX；显卡：RTX 4070；内存：16GB；存储：1TB SSD', 1),
('拯救者R9000P 2025 AI元启', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '联想' limit 1), 11149, '类型：游戏本；处理器：AMD Ryzen 9 8945HX；显卡：RTX 5070；内存：32GB；存储：1TB SSD', 1),
('拯救者Y7000P 2025 AI元启', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '联想' limit 1), 9499, '类型：游戏本；处理器：酷睿 i9 14900HX；显卡：RTX 5060；内存：16GB；存储：1TB SSD', 1),
('小新Pro16GT 2026 AI元启版', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '联想' limit 1), 0, '类型：轻薄本；处理器：酷睿 Ultra X9 388H；显卡：Intel Arc B390；内存：32GB；存储：1TB SSD', 1),
('MateBook X Pro', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 11199, '类型：轻薄本；处理器：酷睿 Ultra 9 185H；显卡：Intel Arc 核显；内存：32GB；存储：2TB SSD', 1),
('MateBook 14', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 6499, '类型：全能本；处理器：酷睿 Ultra 5 125H；显卡：Intel Arc 核显；内存：16GB；存储：1TB SSD', 1),
('MateBook Fold 非凡大师', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 19999, '类型：轻薄本；处理器：麒麟X90；显卡：集成显卡；内存：32GB；存储：2TB SSD', 1),
('MateBook Pro', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '华为' limit 1), 7999, '类型：轻薄本；处理器：麒麟X90；显卡：集成显卡；内存：32GB；存储：1TB SSD', 1),
('XPS 13 2024', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '戴尔' limit 1), 16999, '类型：轻薄本；处理器：酷睿 Ultra 7 258V；显卡：Intel Arc 140V 核显；内存：16GB；存储：1TB SSD', 1),
('Alienware m16 R2', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '戴尔' limit 1), 17999, '类型：游戏本；处理器：酷睿 Ultra 9-185H；显卡：RTX 4070；内存：32GB；存储：1TB SSD', 1),
('Latitude 5440', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '戴尔' limit 1), 7299, '类型：商务本；处理器：酷睿 i7 1355U；显卡：集成显卡；内存：16GB；存储：1TB SSD', 1),
('Latitude 5530', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '戴尔' limit 1), 5699, '类型：商务本；处理器：酷睿 i7 1255U；显卡：集成显卡；内存：32GB；存储：512GB SSD', 1),
('XPS14', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '戴尔' limit 1), 25999, '类型：商务本；处理器：酷睿 UltraX7 358H；显卡：ARC B390；内存：32GB；存储：1TB SSD', 1),
('XPS16', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '戴尔' limit 1), 26999, '类型：商务本；处理器：酷睿 UltraX7 358H；显卡：ARC B390；内存：32GB；存储：1TB SSD', 1),
('星 Book Pro 14', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '惠普' limit 1), 5999, '类型：轻薄本；处理器：酷睿 Ultra 5 225H；显卡：Intel Arc 130T 核显；内存：16GB；存储：1TB SSD', 1),
('暗影精灵 10', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '惠普' limit 1), 8299, '类型：游戏本；处理器：酷睿 i7-14650HX；显卡：RTX 4060；内存：16GB；存储：1TB SSD', 1),
('暗影精灵11', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '惠普' limit 1), 9999, '类型：游戏本；处理器：酷睿 i9 14900HX；显卡：RTX 5070；内存：32GB；存储：1TB SSD', 1),
('战66 2025 酷睿Ultra版 16英寸', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '惠普' limit 1), 6199, '类型：商务本；处理器：酷睿 Ultra 7 155H；显卡：集成显卡；内存：32GB；存储：1TB SSD', 1),
('灵耀 14', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '华硕' limit 1), 7999, '类型：轻薄本；处理器：酷睿 Ultra 7 155H；显卡：Intel Arc 核显；内存：32GB；存储：1TB SSD', 1),
('ROG 魔霸新锐 2025', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '华硕' limit 1), 12999, '类型：游戏本；处理器：锐龙 9 8940HX；显卡：RTX 5070；内存：32GB；存储：1TB SSD', 1),
('ProArt创13 2026', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '华硕' limit 1), 14999, '类型：创作本；处理器：锐龙 AI Max+ 395；显卡：Radeon 8060S；内存：64GB；存储：1TB SSD', 1),
('无畏14 2024', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '华硕' limit 1), 3799, '类型：轻薄本；处理器：酷睿 i5 13500H；显卡：集成显卡；内存：16GB；存储：1TB SSD', 1),
('天选4 13代酷睿版', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '华硕' limit 1), 10499, '类型：游戏本；处理器：酷睿 i9 13900H；显卡：RTX 4060；内存：16GB；存储：1TB SSD', 1),
('ROG 幻16Air 酷睿版', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '华硕' limit 1), 13499, '类型：游戏本；处理器：酷睿 Ultra 9 185H；显卡：RTX 4060；内存：32GB；存储：1TB SSD', 1),
('ROG 幻16Air 锐龙AI版', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '华硕' limit 1), 14999, '类型：游戏本；处理器：Ryzen AI9 HX370；显卡：RTX 4060；内存：32GB；存储：1TB SSD', 1),
('掠夺者 Neo 16', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '宏碁' limit 1), 11999, '类型：游戏本；处理器：酷睿 i9-14900HX；显卡：RTX 4070；内存：32GB；存储：1TB SSD', 1),
('非凡 Go Pro', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '宏碁' limit 1), 6999, '类型：轻薄本；处理器：酷睿 Ultra 7 155H；显卡：Intel Arc 核显；内存：32GB；存储：1TB SSD', 1),
('掠夺者·刀锋8', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '宏碁' limit 1), 19999, '类型：游戏本；处理器：酷睿 Ultra 9 288V；显卡：RTX 5070；内存：32GB；存储：2TB SSD', 1),
('非凡 X14', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '宏碁' limit 1), 7299, '类型：全能本；处理器：酷睿 i5 13500H；显卡：RTX 4050；内存：16GB；存储：1TB SSD', 1),
('蛟龙 16 Pro', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '机械革命' limit 1), 8999, '类型：游戏本；处理器：锐龙 9 7945HX；显卡：RTX 4070；内存：32GB；存储：1TB SSD', 1),
('蛟龙15K', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '机械革命' limit 1), 5699, '类型：游戏本；处理器：Ryzen 7 7735H；显卡：RTX 3050；内存：16GB；存储：512GB SSD', 1),
('无界15X 酷睿版 2024', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '机械革命' limit 1), 6999, '类型：轻薄本；处理器：酷睿 Ultra 7 155H；显卡：集成显卡；内存：32GB；存储：1TB SSD', 1),
('将星 X15 AT', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '七彩虹' limit 1), 6999, '类型：游戏本；处理器：酷睿 i7-14650HX；显卡：RTX 4060；内存：16GB；存储：1TB SSD', 1),
('隐星 P16 TA', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '七彩虹' limit 1), 9999, '类型：游戏本；处理器：酷睿 i9-14900HX；显卡：RTX 4070；内存：32GB；存储：1TB SSD', 1),
('隐星 P16', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '七彩虹' limit 1), 5999, '类型：游戏本；处理器：酷睿 i7 12650H；显卡：RTX 4060；内存：16GB；存储：512GB SSD', 1),
('E14', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '七彩虹' limit 1), 3799, '类型：轻薄本；处理器：Ryzen 7 7735HS；显卡：Radeon 680M；内存：32GB；存储：1TB SSD', 1),
('众颜 U6', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '火影' limit 1), 3999, '类型：轻薄本；处理器：酷睿 i5-12500H；显卡：Intel Iris Xe；内存：16GB；存储：512GB SSD', 1),
('T9 Plus', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '火影' limit 1), 6499, '类型：游戏本；处理器：酷睿 i7-14650HX；显卡：RTX 4060；内存：16GB；存储：1TB SSD', 1),
('众颜U6 2024', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '火影' limit 1), 0, '类型：轻薄本；处理器：Ryzen 7 8845HS；显卡：集成显卡；内存：32GB；存储：1TB SSD', 1),
('T9 系列', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '火影' limit 1), 0, '类型：游戏本；处理器：酷睿 i7；显卡：RTX 系列独显；内存：16GB；存储：1TB SSD', 1),
('MagicBook Pro 16', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '荣耀' limit 1), 8999, '类型：全能本；处理器：酷睿 Ultra 7 155H；显卡：RTX 4060；内存：32GB；存储：1TB SSD', 1),
('MagicBook Pro 14', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '荣耀' limit 1), 5999, '类型：轻薄本；处理器：酷睿 Ultra 5 285H；显卡：Intel Arc 140T核显；内存：16GB；存储：1TB SSD', 1),
('MagicBook Pro 16 2026', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '荣耀' limit 1), 10999, '类型：轻薄本；处理器：酷睿 Ultra X9 388H；显卡：集成显卡；内存：32GB；存储：1TB SSD', 1),
('MagicBook Pro 16 HUNTER版', (select category_id from categories where category_name = '电脑' limit 1), (select brand_id from brands where brand_name = '荣耀' limit 1), 0, '类型：全能本；处理器：酷睿 Ultra 7 155H；显卡：RTX 4060；内存：32GB；存储：1TB SSD', 1);

-- 插入电脑图片
insert into product_images (product_id, image_url, image_name, image_type, is_main, upload_time, status)
values
((select product_id from products where product_name = 'MacBook Air 13 (M3)' limit 1), 'computer_image/MacBook Air M3.png', 'MacBook Air M3.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'MacBook Pro 14 (M4 Pro)' limit 1), 'computer_image/MacBook Pro.jpg', 'MacBook Pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'MacBook Air 13 (M4)' limit 1), 'computer_image/MacBook Air M3.png', 'MacBook Air M3.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'MacBook Pro 13 (M2)' limit 1), 'computer_image/MacBook Pro.jpg', 'MacBook Pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'ThinkPad X1 Carbon' limit 1), 'computer_image/ThinkPad X1 Carbon.jpg', 'ThinkPad X1 Carbon.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '拯救者 Y7000P 2025' limit 1), 'computer_image/拯救者 Y7000P 2025.jpg', '拯救者 Y7000P 2025.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '拯救者R9000P 2025 AI元启' limit 1), 'computer_image/拯救者R9000P 2025 AI元启.jpg', '拯救者R9000P 2025 AI元启.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '拯救者Y7000P 2025 AI元启' limit 1), 'computer_image/拯救者Y7000P 2025 AI元启.jpg', '拯救者Y7000P 2025 AI元启.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '小新Pro16GT 2026 AI元启版' limit 1), 'computer_image/小新Pro16GT 2026 AI元启版.jpg', '小新Pro16GT 2026 AI元启版.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'MateBook X Pro' limit 1), 'computer_image/MateBook X Pro.png', 'MateBook X Pro.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'MateBook 14' limit 1), 'computer_image/MateBook 14.png', 'MateBook 14.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'MateBook Fold 非凡大师' limit 1), 'computer_image/MateBook Fold 非凡大师.png', 'MateBook Fold 非凡大师.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'MateBook Pro' limit 1), 'computer_image/MateBook Pro.png', 'MateBook Pro.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'XPS 13 2024' limit 1), 'computer_image/XPS 13 2024.jpg', 'XPS 13 2024.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'Alienware m16 R2' limit 1), 'computer_image/Alienware m16 R2.jpg', 'Alienware m16 R2.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'Latitude 5440' limit 1), 'computer_image/Latitude 5440.png', 'Latitude 5440.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'Latitude 5530' limit 1), 'computer_image/Latitude 5530.png', 'Latitude 5530.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'XPS14' limit 1), 'computer_image/XPS14.png', 'XPS14.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'XPS16' limit 1), 'computer_image/XPS16.png', 'XPS16.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '星 Book Pro 14' limit 1), 'computer_image/星 Book Pro 14.png', '星 Book Pro 14.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '暗影精灵 10' limit 1), 'computer_image/暗影精灵 10.jpg', '暗影精灵 10.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '暗影精灵11' limit 1), 'computer_image/暗影精灵11.jpg', '暗影精灵11.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '战66 2025 酷睿Ultra版 16英寸' limit 1), 'computer_image/战66 2025 酷睿Ultra版 16英寸.jpg', '战66 2025 酷睿Ultra版 16英寸.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '灵耀 14' limit 1), 'computer_image/灵耀 14.jpg', '灵耀 14.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'ROG 魔霸新锐 2025' limit 1), 'computer_image/ROG 魔霸新锐2025.png', 'ROG 魔霸新锐2025.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'ProArt创13 2026' limit 1), 'computer_image/ProArt创13 2026.jpg', 'ProArt创13 2026.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '无畏14 2024' limit 1), 'computer_image/无畏14 2024.png', '无畏14 2024.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '天选4 13代酷睿版' limit 1), 'computer_image/天选4 13代酷睿版.png', '天选4 13代酷睿版.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'ROG 幻16Air 酷睿版' limit 1), 'computer_image/ROG 幻16Air 酷睿版.jpg', 'ROG 幻16Air 酷睿版.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'ROG 幻16Air 锐龙AI版' limit 1), 'computer_image/ROG 幻16Air 锐龙AI版.jpg', 'ROG 幻16Air 锐龙AI版.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '掠夺者 Neo 16' limit 1), 'computer_image/掠夺者 Neo 16.jpg', '掠夺者 Neo 16.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '非凡 Go Pro' limit 1), 'computer_image/非凡 Go Pro.jpg', '非凡 Go Pro.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '掠夺者·刀锋8' limit 1), 'computer_image/掠夺者·刀锋8.jpg', '掠夺者·刀锋8.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '非凡 X14' limit 1), 'computer_image/非凡 X14.jpg', '非凡 X14.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '蛟龙 16 Pro' limit 1), 'computer_image/蛟龙 16 Pro.png', '蛟龙 16 Pro.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '蛟龙15K' limit 1), 'computer_image/蛟龙15K.png', '蛟龙15K.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '无界15X 酷睿版 2024' limit 1), 'computer_image/无界15X 酷睿版 2024.png', '无界15X 酷睿版 2024.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '将星 X15 AT' limit 1), 'computer_image/将星 X15 AT.png', '将星 X15 AT.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '隐星 P16 TA' limit 1), 'computer_image/隐星 P16 TA.png', '隐星 P16 TA.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '隐星 P16' limit 1), 'computer_image/隐星 P16.png', '隐星 P16.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'E14' limit 1), 'computer_image/E14.png', 'E14.png', 'png', 1, now(), 1),
((select product_id from products where product_name = '众颜 U6' limit 1), 'computer_image/众颜 U6.jpg', '众颜 U6.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'T9 Plus' limit 1), 'computer_image/T9 Plus.jpg', 'T9 Plus.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = '众颜U6 2024' limit 1), 'computer_image/众颜U6 2024.jpg', '众颜U6 2024.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'T9 系列' limit 1), 'computer_image/T9 系列.jpg', 'T9 系列.jpg', 'jpg', 1, now(), 1),
((select product_id from products where product_name = 'MagicBook Pro 16' limit 1), 'computer_image/MagicBook Pro 16.png', 'MagicBook Pro 16.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'MagicBook Pro 14' limit 1), 'computer_image/MagicBook Pro 14.png', 'MagicBook Pro 14.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'MagicBook Pro 16 2026' limit 1), 'computer_image/MagicBook Pro 16 2026.png', 'MagicBook Pro 16 2026.png', 'png', 1, now(), 1),
((select product_id from products where product_name = 'MagicBook Pro 16 HUNTER版' limit 1), 'computer_image/MagicBook Pro 16.png', 'MagicBook Pro 16.png', 'png', 1, now(), 1);

-- 添加用户
insert into users
values(114510,'gin','123456','15860827759','cole36620@gmail.com','男',1,now());
-- 添加管理员
insert into admin
values(1,'admin1','123456','3277314262@qq.com','超级管理员',1),
(2,'admin2','123456','1145144@163.com','普通管理员',1);;